#!/usr/bin/env python3
"""Generate docs/api-reference.md from srxy.__all__.

Regenerate:

	python scripts/docs/export_public_api.py
"""

from __future__ import annotations

import dataclasses
import enum
import inspect
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "api-reference.md"

HEADER = """\
<!-- Generated by scripts/docs/export_public_api.py — do not edit by hand. -->

# Public API reference

Stable symbols re-exported from `srxy` (`srxy.__all__`). Regenerate with:

```bash
python scripts/docs/export_public_api.py
```

"""


def _format_annotation(annotation: Any) -> str:
	if annotation is inspect.Parameter.empty:
		return ""
	if isinstance(annotation, type):
		return annotation.__name__
	text = str(annotation)
	for prefix in ("typing.", "pathlib.", "collections.abc.", "srxy.domain.models.", "srxy.domain.progress."):
		text = text.replace(prefix, "")
	return text


def _format_default(default: Any) -> str:
	if default is inspect.Parameter.empty:
		return ""
	if isinstance(default, enum.Enum):
		return f"{type(default).__name__}.{default.name}"
	if default is None or isinstance(default, bool | int | float | str):
		return repr(default)
	name = getattr(default, "__name__", "")
	if name == "<lambda>" or "factory" in repr(default).lower():
		return "..."
	return repr(default)


def _signature_for_callable(obj: Callable[..., Any], *, display_name: str | None = None) -> str:
	try:
		sig = inspect.signature(obj)
	except (TypeError, ValueError):
		return f"{display_name or obj.__name__}(...)"
	parts: list[str] = []
	keyword_only_marker = False
	for name, param in sig.parameters.items():
		if name == "self":
			continue
		if param.kind is inspect.Parameter.KEYWORD_ONLY and not keyword_only_marker:
			parts.append("*")
			keyword_only_marker = True
		piece = name
		annotation = _format_annotation(param.annotation)
		if annotation:
			piece = f"{piece}: {annotation}"
		if param.default is not inspect.Parameter.empty:
			piece = f"{piece} = {_format_default(param.default)}"
		if param.kind is inspect.Parameter.VAR_POSITIONAL:
			piece = f"*{name}"
			if annotation:
				piece = f"*{name}: {annotation}"
		elif param.kind is inspect.Parameter.VAR_KEYWORD:
			piece = f"**{name}"
			if annotation:
				piece = f"**{name}: {annotation}"
		parts.append(piece)
	return_annotation = _format_annotation(sig.return_annotation)
	if return_annotation in {"", "None"}:
		suffix = ""
	else:
		suffix = f" -> {return_annotation}"
	return f"{display_name or obj.__name__}({', '.join(parts)}){suffix}"


def _explicit_docstring(obj: Any) -> str:
	"""Return a hand-written docstring only (skip dataclass auto-docs)."""
	if isinstance(obj, type):
		doc = obj.__dict__.get("__doc__")
	else:
		doc = getattr(obj, "__doc__", None)
	if not doc:
		return ""
	return inspect.cleandoc(doc).strip()


def _render_function(name: str, obj: Callable[..., Any]) -> str:
	lines = [
		f"## `{name}`",
		"",
		"```python",
		_signature_for_callable(obj, display_name=name),
		"```",
		"",
	]
	doc = _explicit_docstring(obj)
	if doc:
		lines.extend([doc, ""])
	return "\n".join(lines)


def _render_enum(name: str, obj: type[enum.Enum]) -> str:
	lines = [
		f"## `{name}`",
		"",
		f"Enum (`{obj.__module__}.{obj.__qualname__}`)",
		"",
	]
	doc = _explicit_docstring(obj)
	if doc:
		lines.extend([doc, ""])
	lines.append("Members:")
	lines.append("")
	for member in obj:
		lines.append(f"- `{member.name}` = `{member.value!r}`")
	lines.append("")
	return "\n".join(lines)


def _render_dataclass(name: str, obj: type[Any]) -> str:
	lines = [
		f"## `{name}`",
		"",
		f"Dataclass (`{obj.__module__}.{obj.__qualname__}`)",
		"",
	]
	doc = _explicit_docstring(obj)
	if doc:
		lines.extend([doc, ""])
	lines.extend(
		[
			"```python",
			_signature_for_callable(obj.__init__, display_name=name),
			"```",
			"",
		]
	)
	fields = dataclasses.fields(obj)
	if fields:
		lines.append("Fields:")
		lines.append("")
		for field in fields:
			annotation = _format_annotation(field.type)
			type_part = f": `{annotation}`" if annotation else ""
			lines.append(f"- `{field.name}`{type_part}")
		lines.append("")
	return "\n".join(lines)


def _render_class(name: str, obj: type[Any]) -> str:
	if issubclass(obj, enum.Enum):
		return _render_enum(name, obj)
	if dataclasses.is_dataclass(obj):
		return _render_dataclass(name, obj)
	lines = [
		f"## `{name}`",
		"",
		f"Class (`{obj.__module__}.{obj.__qualname__}`)",
		"",
	]
	doc = _explicit_docstring(obj)
	if doc:
		lines.extend([doc, ""])
	return "\n".join(lines)


def render_public_api_markdown() -> str:
	import srxy

	sections = [HEADER]
	for name in sorted(srxy.__all__):
		obj = getattr(srxy, name)
		if inspect.isclass(obj):
			sections.append(_render_class(name, obj))
		elif callable(obj):
			sections.append(_render_function(name, obj))
		else:
			sections.append(f"## `{name}`\n\n`{obj!r}`\n")
	return "\n".join(sections).rstrip() + "\n"


def main() -> int:
	sys.path.insert(0, str(ROOT / "src"))
	markdown = render_public_api_markdown()
	OUTPUT.write_text(markdown, encoding="utf-8")
	print(f"Wrote {OUTPUT.relative_to(ROOT)}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
